/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:81b94d14-fd14-47eb-a5bc-879c3182a763",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_9SfPHO7qi",
    "aws_user_pools_web_client_id": "67il9m3sc0rb3e1jqvu4oo2th3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ebtwjvd4l5cwtmqgjymio4u5ia.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4itfvvdqtbatjkvwuhrhtclpae",
    "aws_user_files_s3_bucket": "twitter-clone110815-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
